export interface MockDataPropsType {
    id: number;
    image?: string;
    title: string;
    description: string;
    price: number;
    region: string;
    city: string;
    address: string;
    comission?: number;
    phone: number;
    email: string;
}

export const MockData: MockDataPropsType[] = [
    {
        id: 1,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 2,
        image: "http://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bW9kZXJuJTIwaG91c2V8ZW58MHx8MHx8&w=1000&q=80",
        title: "House for rent 4 rooms",
        description:
            "That beautiful villa offered for rent is placed in the north part of Bucharest near Baneasa forest, walking distance from Iancu Nicolae street, close to British School, Jollie Ville Mall and many restaurants. ",
        price: 421,
        region: "HR",
        city: "Gheorgheni",
        address: "Bucin negyed 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 3,
        image: "http://cf.bstatic.com/xdata/images/hotel/max1024x768/314234937.jpg?k=3a1bc77e40b4a7f18a7746999bb0e932becdedfa57df23820349ab09afb621ee&o=&hp=1",
        title: "Apartment for rent 2 rooms",
        description:
            "At the beginning of the twentieth century under the careful design and enterprise of architects August Ferdinand Schmiedigen and George Matei Cantacuzino was founded the Palace of Nicolae Mavrocordat, in the vision of its first owner, the engineer Nicolae Mavrocordat.",
        price: 421,
        region: "HR",
        city: "Odorhei Secuiesc",
        address: "Petofi utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 4,
        image: "http://www.real-estate-costa-blanca.com/uploaded_files/photos/fe4edcd654c99506f068af26a2c525c5_photo_760x1140_wt.JPG",
        title: "Villa for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 5,
        image: "http://cdn.vox-cdn.com/thumbor/frFQQhOsxl8DctGjkR8OLHpdKMs=/0x0:3686x2073/1200x800/filters:focal(1549x743:2137x1331)/cdn.vox-cdn.com/uploads/chorus_image/image/68976842/House_Tour_Liverman_3D6A3138_tour.0.jpg",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 6,
        image: "http://images.adsttc.com/media/images/5ecd/d4ac/b357/65c6/7300/009d/large_jpg/02C.jpg?1590547607",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 7,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 8,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 9,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 10,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 11,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 12,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 13,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 14,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 15,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 16,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 17,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 18,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 19,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 20,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 21,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 22,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 23,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 24,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 25,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 26,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 27,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 28,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 29,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 30,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 31,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 32,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 33,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 34,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 35,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 36,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 37,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 38,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 39,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 40,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 41,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 42,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 43,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 44,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 45,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 46,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 47,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 48,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 49,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
    {
        id: 50,
        image: "http://images.adsttc.com/media/images/63c0/a935/7643/4a39/8498/948f/large_jpg/casa-tunich-apiron_13.jpg?1673570670",
        title: "Property for rent 2 rooms",
        description:
            "Property for rent situated in Dorobanti - Aviatorilor area, Bucharest, benefiting of a great location and easy access to all the important point of interest in the city.",
        price: 421,
        region: "HR",
        city: "Miercurea-Ciuc",
        address: "Kossuth utca 4",
        comission: 828,
        phone: 2513626949,
        email: "gatteridge0@prnewswire.com",
    },
];
